steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Building container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/temusrag/temus-case-study-registry/temus-case-study-image',
    '-f',
    'Dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/temusrag/temus-case-study-registry/temus-case-study-image'
  ]
