steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Building backend container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/temusrag/temus-case-study-registry/backend',
    '-f',
    'backend.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Pushing backend container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/temusrag/temus-case-study-registry/backend'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploying backend to Compute Engine'
  waitFor: ["Pushing backend container image"]
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud compute instances create-with-container backend-instance-ce \
        --project=temusrag \
        --zone=europe-west1-b \
        --machine-type=e2-medium \
        --network-interface=network-tier=PREMIUM,stack-type=IPV4_ONLY,subnet=default \
        --maintenance-policy=MIGRATE \
        --provisioning-model=STANDARD \
        --service-account=328408150766-compute@developer.gserviceaccount.com \
        --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append \
        --tags=http-server,https-server,lb-health-check \
        --image=projects/cos-cloud/global/images/cos-101-17162-463-42 \
        --boot-disk-size=50GB \
        --boot-disk-type=pd-balanced \
        --boot-disk-device-name=backend-instance-ce \
        --container-image=europe-west1-docker.pkg.dev/temusrag/temus-case-study-registry/backend:latest \
        --container-restart-policy=always \
        --no-shielded-secure-boot \
        --shielded-vtpm \
        --shielded-integrity-monitoring \
        --labels=goog-ec-src=vm_add-gcloud,container-vm=cos-101-17162-463-42

- name: 'gcr.io/cloud-builders/docker'
  id: 'Building frontend container image'
  waitFor: ["Deploying backend to Compute Engine"]
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/temusrag/temus-case-study-registry/frontend',
    '-f',
    'frontend.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Pushing frontend container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/temusrag/temus-case-study-registry/frontend'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploying frontend to Cloud Run'
  waitFor: ["Pushing frontend container image"]
  args: [
    'run',
    'deploy',
    'frontend',
    '--image',
    'europe-west1-docker.pkg.dev/temusrag/temus-case-study-registry/frontend:latest',
    '--region',
    'europe-west1',
    '--platform',
    'managed',
    '--allow-unauthenticated'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
