steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Building backend container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/temusrag/temus-case-study-registry/backend',
    '-f',
    'backend.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Pushing backend container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/temusrag/temus-case-study-registry/backend'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploying backend to Cloud Run'
  waitFor: ["Pushing backend container image"]
  args: [
    'run',
    'deploy',
    'backend',
    '--image',
    'europe-west1-docker.pkg.dev/temusrag/temus-case-study-registry/backend:latest',
    '--region',
    'europe-west1',
    '--platform',
    'managed',
    '--allow-unauthenticated'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'Building frontend container image'
  waitFor: ["Deploying backend to Cloud Run"]
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/temusrag/temus-case-study-registry/frontend',
    '-f',
    'frontend.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Pushing frontend container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/temusrag/temus-case-study-registry/frontend'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploying frontend to Cloud Run'
  waitFor: ["Pushing frontend container image"]
  args: [
    'run',
    'deploy',
    'frontend',
    '--image',
    'europe-west1-docker.pkg.dev/temusrag/temus-case-study-registry/frontend:latest',
    '--region',
    'europe-west1',
    '--platform',
    'managed',
    '--allow-unauthenticated'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
